version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Docker Build
          command: |
            bash config/ci/deploy.sh prod docker-build

      - run: bash config/ci/deploy.sh prod docker-push
      - run: bash config/ci/deploy.sh prod deploy
